apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redpanda-console.fullname" . }}
  labels:
    app: {{ include "redpanda-console.name" . }}
    chart: {{ include "redpanda-console.chart" . }}
    release: {{ .Release.Name }}
data:
  config.yaml: |
    kafka:
      brokers:
        {{- range .Values.kafka.brokers }}
        - {{ . | quote }}
        {{- end }}
      {{- if .Values.kafka.sasl.enabled }}
      sasl:
        enabled: true
        mechanism: {{ .Values.kafka.sasl.mechanism }}
        username: {{ .Values.kafka.sasl.username }}
        password: {{ .Values.kafka.sasl.password }}
      {{- end }}
    {{- if .Values.connect.enabled }}
    kafkaConnect:
      enabled: true
      clusters:
        {{- range .Values.connect.clusters }}
        - name: {{ .name }}
          url: {{ .url }}
        {{- end }}
    {{- end }}
